services:
  webserver:
    image: "php:8.2-apache"
    ports: 
      - "9000:80"
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: concurrency_example 
    ports: 
      - "3306:3306"

